name: Build and Run CPP

on:
    pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - run: g++ hello_world/cpp/hello_world.cpp -o hello 
        - run: ./hello
        - run: rm hello