name: Build and Run Java

on:
    push:
      branches: [ $default-branch ]
    pull_request:
      branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'
        - run: java HelloWorldApp.java