name: Build and Run Rust

on:
    pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - run: rustc hello_world/rust/hello_world.rs -o hello
        - run: hello